### ISSUE TITLE
RequestEnricherInterface broken

### ISSUE THREAD

**Issue by cm-andrews** [FriendsOfTYPO3/feedit#11]
When activating feedit in a new Typo3v10.4.6 installation numerous errors are thrown concerning the RequestEnricherInterface

PHP Fatal error:  Interface 'TYPO3\\CMS\\Feedit\\Modules\\RequestEnricherInterface' not found in /typo3conf/ext/feedit/Classes/Modules/EditModule.php

The import is missing. After Adding the Import the error changes to:

Return value of TYPO3\CMS\Feedit\Modules\EditModule::enrich() must implement interface Psr\Http\Message\ServerRequestInterface, none returned

I didn't examine the issue further.

Is this extension ready for use or is this just a WIP fork?

**Comment by ohader** [comment]
Probably a duplicate of PR https://github.com/FriendsOfTYPO3/feedit/pull/9

**Comment by cm-andrews** [comment]
Integrated the PR locally. Fixes the initial issue, but others pop up when trying to actually edit elements. They are caused in typo3/sysext/backend/Resources/Public/JavaScript/ContextHelp.js.
