### ISSUE TITLE
Question about TYPO3 V11 Compatibility

### ISSUE THREAD

**Issue by Christian-HW** [FriendsOfTYPO3/feedit#15]
Hi,

are there any plans to update feedit for TYPO3 v11.5 yet?

Kind regards,

Christian

**Comment by georgringer** [comment]
if there is interest in it I could look into it

**Comment by klodeckl** [comment]
@Christian-HW please check branch called 11-12. Works flawless, good work @georgringer. Could be published in TER and packagist I think.
